spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLongForProductionUse}
  expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${PORT:8080}
